version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shorten_url
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "5306:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/shorten_url"
    ports:
      - "5001:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: shorten_url
      DB_PASSWORD: password
      DB_HOST: db
